#!/bin/sh

# Background
gsettings set org.gnome.desktop.background picture-options "zoom"
# gsettings set org.gnome.desktop.background picture-uri "file://"

# UI
gsettings set org.gnome.desktop.interface can-change-accels true
gsettings set org.gnome.desktop.interface cursor-blink false
gsettings set org.gnome.desktop.interface icon-theme "elementary-xfce"
gsettings set org.gnome.desktop.interface gtk-theme "TLS_Quantal"
gsettings set org.gnome.desktop.interface toolbar-icon-size "small"

# Font
gsettings set org.gnome.settings-daemon.plugins.xsettings antialiasing rgba
gsettings set org.gnome.settings-daemon.plugins.xsettings hiting slight

gsettings set org.gnome.desktop.interface document-font-name "PT Sans 11"
gsettings set org.gnome.desktop.interface font-name "PT Sans 11"
gsettings set org.gnome.desktop.interface monospace-font-name "DejaVu Sans Mono 11"

# Keyboard
gsettings set org.gnome.desktop.input-sources sources "[('xkb','us')]"
gsettings set org.gnome.desktop.input-sources xkb-options "['terminate:ctrl_alt_bksp','caps:ctrl_modifier']"

# Touch Pad
gsettings set org.gnome.settings-daemon.peripherals.touchpad tap-to-click true
# gsettings set org.gnome.settings-daemon.peripherals.touchpad disable-while-typing true
gsettings set org.gnome.settings-daemon.peripherals.touchpad scroll-method "two-finger-scrolling"
gsettings set org.gnome.settings-daemon.peripherals.touchpad horiz-scroll-enabled true
gsettings set org.gnome.settings-daemon.peripherals.touchpad natural-scroll true

# Power Management
gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-ac-timeout 1800
gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-battery-timeout 600
gsettings set org.gnome.settings-daemon.plugins.power button-power "interactive"
gsettings set org.gnome.settings-daemon.plugins.power lid-close-ac-action "blank"
gsettings set org.gnome.settings-daemon.plugins.power lid-close-suspend-with-external-monitor true

# Typing Break
gsettings set org.gnome.settings-daemon.plugins.typing-break enabled true
gsettings set org.gnome.settings-daemon.plugins.typing-break allow-postpone true
gsettings set org.gnome.settings-daemon.plugins.typing-break break-time 300
gsettings set org.gnome.settings-daemon.plugins.typing-break type-time 1500

# Misc
xdg-user-dirs-update --set DESKTOP $HOME/Desktop
xdg-user-dirs-update --set DOWNLOAD $HOME/Download
xdg-user-dirs-update --set DOCUMENTS $HOME/Documents
xdg-user-dirs-update --set MUSIC $HOME/Music
xdg-user-dirs-update --set PICTURES $HOME/Pictures
xdg-user-dirs-update --set VIDEOS $HOME/Videos

