#!/usr/bin/env bash

if [ -z "$PS1" ]; then
  echo -e "\033[0;31mYou should source this, not run it, for example: source ./install\033[m"
else
  link (){
    if [ -e $1 ]; then
      if [ -e "$2" ]; then
        rm "$2"
      fi

      ln -s "$1" "$2"
    fi
  }

  source $HOME/cli/shell/common.sh

  # bash
  link $CLI/bash/bash_profile $HOME/.bash_profile
  link $CLI/bash/bashrc $HOME/.bashrc

  # zsh
  link $CLI/zsh/zshrc $HOME/.zshrc

  # vim
  link $CLI/vim/vimrc $HOME/.vimrc
  link $CLI/vim $HOME/.vim
  # link $CLI/vim/gvimrc $HOME/.gvimrc
  echo "set t_vb=" >> ~/.gvimrc
  link $CLI/linux/xmodmap $HOME/.xmodmap

  # tmux
  link $CLI/tmux/tmux.conf $HOME/.tmux.conf

  # git
  link $CLI/git/gitconfig $HOME/.gitconfig
  link $CLI/git/gitignore $HOME/.gitignore

  # ruby
  link $CLI/ruby/gemrc $HOME/.gemrc
  link $CLI/ruby/irbrc $HOME/.irbrc
  link $CLI/ruby/pryrc $HOME/.pryrc

  # if [ "$OS" = "darwin" ]; then
  #   cat $CLI/Custom.css > "$HOME/Library/Application Support/Google/Chrome/Default/User StyleSheets/Custom.css"
  # fi

  if [ "$OS" = "linux" ]; then
    link $CLI/awesome $HOME/.config/awesome
    link $CLI/x/xinitrc $HOME/.xinitrc
    link $CLI/x/xresources $HOME/.xresources
    link $CLI/x/xmodmap $HOME/.xmodmap
    # link $CLI/x/terminalrc $HOME/.config/xfce4/terminal/terminalrc
    # cat $CLI/Custom.css > "$HOME/.config/google-chrome/Default/User StyleSheets/Custom.css"
  fi
fi

