#!/bin/sh

source /etc/X11/xinit/xinitrc.d/30-dbus

xrdb -merge $HOME/.xresources
xrandr --output LVDS --set BACKLIGHT 6

xfsettingsd
xfce4-power-manager
xfce4-volumed
xcalib -d :0 $HOME/local/9CA4.icc
#xflux -l 21.0 -g 105.8 -nofork &

eval $(/usr/bin/gnome-keyring-daemon --start --components=gpg,pkcs11,ssh)
export SSH_AUTH_SOCK
export GPG_AGENT_INFO
export GNOME_KEYRING_CONTROL
export GNOME_KEYRING_PID

systemd --user &

kupfer &
dropboxd &
# emacs --daemon &
thunar --daemon &
$HOME/local/bin/rescuetime &
# compton -e 1 &

xmodmap $HOME/.xmodmap
# setxkbmap -option "terminate:ctrl_alt_bksp','caps:ctrl_modifier"
xcape -e 'Control_R=Escape' &

source $HOME/.fehbg

wmname LG3D
exec awesome --no-argb
